name: Deploy Blazor WASM to GitHub Pages

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.200

      - name: Restore packages
        run: dotnet restore /Paymongo.Sharp.BlazorWasm.Sample/Paymongo.Sharp.BlazorWasm.Sample.csproj

      - name: Publish .NET Core Project
        run: dotnet publish /Paymongo.Sharp.BlazorWasm.Sample/Paymongo.Sharp.BlazorWasm.Sample.csproj -c Release -o release

      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: /Paymongo.Sharp.BlazorWasm.Sample/release/wwwroot